---
abstract: 'Pull author contribution counts for github repos'
author:
  - justin.d.hunter@gmail.com
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Github-Score
requires:
  Data::Dumper: 0
  HTTP::Request: 0
  JSON: 0
  LWP: 0
  Moose: 0
  URI: 0
  strict: 0
  warnings: 0
version: 0.2.0
